apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendxss-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendxss
  template:
    metadata:
      labels:
        app: frontendxss
    spec:
      containers:
        - name: frontend-container
          image: wellstrey/frontendxss:latest
          ports:
            - containerPort: 3000
