apiVersion: v1
kind: Service
metadata:
  name: xss-playground
spec:
  type: NodePort
  selector:
    app: xss-playground
  ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 80     # Container port (matches EXPOSE in Dockerfile)
      nodePort: 30080    # Node port to access externally (can be any port 30000-32767)
