apiVersion: v1
kind: Service
metadata:
  name: frontendxss-service
spec:
  type: NodePort
  selector:
    app: frontendxss
  ports:
    - protocol: TCP
      port: 3000           # Service port
      targetPort: 3000     # Container port (matches EXPOSE in Dockerfile)
      nodePort: 30080    # Node port to access externally (can be any port 30000-32767)
